### ISSUE TITLE
Use relative paths for images

### ISSUE THREAD

**Issue by salishdev** [majr-tech/com#1]
We can use relative paths for images so they aren't pointing at a specific commit.
For example, in 

https://github.com/majr-tech/com/blob/cd8686cafe74e79711ae7e67e083f81430c946c3/investor/01-Updates/11-2-22.md?plain=1#L50

you should be able to use:

```markdown
![Merch QR Code Test](../images/qrcode.png)
```

**Comment by salishdev** [comment]
Same also works for linking to other markdown files. Though I'm not sure it works for directories.

**Comment by progmanexe** [comment]
Thanks Jeremy!
